INSERT INTO "Actor" (name, "createdAt") VALUES
('Leonardo DiCaprio', NOW()),
('Meryl Streep', NOW()),
('Robert Downey Jr.', NOW()),
('Scarlett Johansson', NOW()),
('Tom Hanks', NOW()),
('Natalie Portman', NOW()),
('Brad Pitt', NOW()),
('Jennifer Lawrence', NOW()),
('Will Smith', NOW()),
('Emma Stone', NOW()),
('Ryan Reynolds', NOW()),
('Margot Robbie', NOW()),
('Denzel Washington', NOW()),
('Sandra Bullock', NOW()),
('Chris Evans', NOW()),
('Charlize Theron', NOW()),
('Matt Damon', NOW()),
('Amy Adams', NOW()),
('Ryan Gosling', NOW()),
('Gal Gadot', NOW());